spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@<database-url>:<sid>
    username: <username>
    password: <password>
  jpa:
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        default_schema: <default-schema>
        current_session_context_class: thread
        dialect: org.hibernate.spatial.dialect.oracle.OracleSpatial10gDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        type: trace
server.port: 10088

flyway:
  url: jdbc:oracle:thin:@<database-url>:<sid>
  locations: db/migration
  username: <username>
  password: <password>
  baseline-on-migrate: true

logging:
  level:
    org:
      hibernate:
        type: trace
