
const earthquakeColumnDefinitions = {
  year: {
    title: "Year",
    validValues:  "-2150 to <current year>",
    data: "Format +/-yyyy (-is B.C, +is A.D.)\n" +
    "The Date and Time are given in Universal Coordinated Time (also known as Greenwich Mean Time). The local date may be one day different."
  },
  month: {
    title: "Month",
    validValues: "1 to 12",
    data: "The Date and Time are given in Universal Coordinated Time (also known as Greenwich Mean Time). The local date may be one day different."
  },
  day: {
    title: 'Day',
    validValues: '1-31',
    data: "The Date and Time are given in Universal Coordinated Time (also known as Greenwich Mean Time). The local date may be one day different."
  },
  hour: {
    title: 'Hr',
    validValues: '0-23',
    data: "The Date and Time are given in Universal Coordinated Time (also known as Greenwich Mean Time). The local date may be one day different."
  },
  minute: {
    title: 'Min',
    validValues: '0-59',
    data: "The Date and Time are given in Universal Coordinated Time (also known as Greenwich Mean Time). The local date may be one day different."
  },
  second: {
    title: 'Sec',
    validValues: '0-59',
    data: "The Date and Time are given in Universal Coordinated Time (also known as Greenwich Mean Time). The local date may be one day different."
  },
  locationName: {
    title: "Geographic Location",
    validValues: null,
    data: "The Country, State, Province or City where the Earthquake occurred (For example enter: USA or California or San Francisco)\n" +
    "This is only an approximate geographic location. Events prior to 1900 were not instrumentally located, therefore, the location given is based on the latitude and longitude of the city where the damage occurred. In the Geographic Location column, the country is listed first, then the province or state, and finally the city or cities where damage was reported. If there are different spellings of a city name the additional spellings are in parentheses."
  },
  latitude: {
    title: "Latitude",
    validValues: '-90 to 90',
    data: "Latitude: 0 to 90 (Northern Hemisphere) -90 to 0 (Southern Hemisphere)\n" +
    "\n" +
    "Events prior to 1900 were not instrumentally located, therefore, the location given is based on the latitude and longitude of the city where the damage occurred.\n" +
    "\n" +
    "The event coordinates of approximately 100 earthquakes in this database are not known and the latitude and longitude are listed as 0.0. Therefore, to retrieve all the events from a particular country or state, leave the event coordinates search parameter blank and enter the country."
  },
  longitude: {
    title: "Longitude",
    validValues: '-180 to 180',
    data: "Longitude: 0 to 180 (Eastern Hemisphere) -180 to 0 (Western Hemisphere)\n" +
    "\n" +
    "Events prior to 1900 were not instrumentally located, therefore, the location given is based on the latitude and longitude of the city where the damage occurred.\n" +
    "\n" +
    "The event coordinates of approximately 100 earthquakes in this database are not known and the latitude and longitude are listed as 0.0. Therefore, to retrieve all the events from a particular country or state, leave the event coordinates search parameter blank and enter the country."
  },
  eqDepth: {
    title: "Focal Depth (km)",
    validValues: "0 to 700km",
    data:"The depth of the earthquake is given in kilometers."
  },
  eqMagnitude: {
    title: "Earthquake Magnitude",
    validValues: "0.0 to 9.9",
    data: "The value in this column contains the primary earthquake magnitude. Magnitude measures the energy released at the source of the earthquake. Magnitude is determined from measurements on seismographs. For pre-instrumental events, the magnitudes are derived from intensities. There are several different scales for measuring earthquake magnitudes. The primary magnitude is chosen from the available magnitude scales in this order:\n",
  },
  intensity: {
    title: 'MMI Intensity',
    validValues: '1 to 12',
    data: 'TBD'
  },
  relatedTsunmai: {
    title: 'Associated Tsunami or Seiche',
    validValues: null,
    data: 'When a tsunami or seiche was generated by an earthquake, "Tsu" appears in the Assoc Tsu column which is linked to the tsunami event database. The Tsu link will display additional tsunami event information in a new browser window.'
  },
  relatedVolcano: {
    title: 'Volcano',
    validValues: null,
    data: 'The Volcano link will display additional information in a new browser window if the tsunami was associated with an volcanic eruption. The information may include information such as the VEI index, morphology, and the effects of the eruption.'
  },
  deaths: {
    title: 'Number of Deaths from the Earthquake',
    validValues: '0 to 1100000',
    data: 'Whenever possible, numbers of deaths are listed. When references give different death tolls, each death toll and corresponding reference is listed as a separate record.'
  },
  deathsAmountOrder: {
    title: 'Description of Deaths from the Earthquake',
    validValues: '0 to 4',
    data: 'When a description was found in the historical literature instead of an actual number of deaths, this value was coded and listed in the Deaths De column. If the actual number of deaths was listed, a descriptor was also added for search purposes.\n' +
    '\n' +
    '0 = None\n' +
    '1 = Few (~1 to 50 deaths)\n' +
    '2 = Some (~51 to 100 deaths)\n' +
    '3 = Many (~101 to 1000 deaths)\n' +
    '4 = Very Many (~1001 or more deaths)'
  },
  injuries: {
    title: 'Number of Injuries from the Earthquake',
    validValues: '0 to 30000',
    data: 'Whenever possible, numbers of injuries from the earthquake are listed.'
  },
  injuriesAmountOrder: {
    title: 'Description of Injuries from the Earthquake',
    validValues: '0 to 4',
    data: 'When a description was found in the historical literature instead of an actual number of injuries, this value was coded and listed in the Injuries De column. If the actual number of injuries was listed, a descriptor was also added for search purposes.\n' +
    '\n' +
    '0 = None\n' +
    '1 = Few (~1 to 50 injuries)\n' +
    '2 = Some(~51 to 100 injuries)\n' +
    '3 = Many (~101 to 1000 injuries)\n' +
    '4 = Very Many (~1001 or more injuries)\n'
  },
  damageMillionsDollars: {
    title: 'Damage in Millions of Dollars from the Earthquake',
    validValues: null,
    data: 'The value in the Damage column should be multipled by 1,000,000 to obtain the actual dollar amount.\n' +
    '\n' +
    'When a dollar amount for damage was found in the literature, it was listed in the Damage column in millions of U.S. dollars. The dollar value listed is the value at the time of the event. To convert the damage to current dollar values, please use the Consumer Price Index Calculator. Monetary conversion tables for the time of the event were used to convert foreign currency to U.S. dollars.'
  },
  damageAmountOrder: {
    title: 'Description of Damage from the Earthquake',
    validValues: '0 to 4',
    data: 'For those events not offering a monetary evaluation of damage, the following five-level scale was used to classify damage (1990 dollars) and was listed in the Damage De column. If the actual dollar amount of damage was listed, a descriptor was also added for search purposes.\n' +
    '\n' +
    '0 = NONE\n' +
    '1 = LIMITED (roughly corresponding to less than $1 million)\n' +
    '2 = MODERATE (~$1 to $5 million)\n' +
    '3 = SEVERE (~>$5 to $24 million)\n' +
    '4 = EXTREME (~$25 million or more)\n' +
    'When possible, a rough estimate was made of the dollar amount of damage based upon the description provided, in order to choose the damage category. In many cases, only a single descriptive term was available. These terms were converted to the damage categories based upon the authors apparent use of the term elsewhere. In the absence of other information, LIMITED is considered synonymous with slight, minor, and light, SEVERE as synonymous with major, extensive, and heavy, and EXTREME as synonymous with catastrophic.\n' +
    '\n' +
    'Note: The descriptive terms relate approximately to current dollar values.'
  },
  housesDestroyed: {
    title: 'Total Number of Houses Destroyed by the Earthquake',
    validValues: '0 to 1100000',
    data: 'Whenever possible, numbers of houses destroyed are listed.'
  },
  housesAmountOrder: {
    title: 'Description of Houses Destroyed by the Earthquake',
    validValues: '0 to 4',
    data: 'For those events not offering an exact number of houses destroyed, the following four-level scale was used to classify the destruction and was listed in the Houses Destroyed De column. If the actual number of houses destroyed was listed, a descriptor was also added for search purposes.\n' +
    '\n' +
    '0 = None\n' +
    '1 = Few (~1 to 50 houses)\n' +
    '2 = Some (~51 to 100 houses)\n' +
    '3 = Many (~101 to 1000 houses)\n' +
    '4 = Very Many (~1001 or more houses)'
  },
  housesDamaged: {
    title: 'Total Number of Houses Damaged by the Earthquake',
    validValues: '0 to 1100000',
    data: 'Whenever possible, numbers of houses damaged are listed.'
  },
  housesDamagedAmountOrder: {
    title: 'Description of Houses Damaged by the Earthquake',
    validValues: '0 to 4',
    data: 'For those events not offering an exact number of houses damaged, the following four-level scale was used to classify the damage and was listed in the Houses Damaged De column. If the actual number of houses destroyed was listed, a descriptor was also added for search purposes.\n' +
    '\n' +
    '0 = None\n' +
    '1 = Few (~1 to 50 houses)\n' +
    '2 = Some (~51 to 100 houses)\n' +
    '3 = Many (~101 to 1000 houses)\n' +
    '4 = Very Many (~1001 or more houses)'
  }
};

export {
  earthquakeColumnDefinitions
}